######################################################################
# Automatically generated by qmake (3.0) Sun Dec 1 12:43:18 2019
######################################################################

TEMPLATE = lib
TARGET = tools
QT += widgets
INCLUDEPATH += ../incl ../../main/incl
CONFIG += staticlib
DESTDIR = ../../lib

# Input
SOURCES += fpos_input_manager.cpp \
           fpos_screen.cpp \
           fpos_screen_qt.cpp \
           fpos_screen_qt.moc.cpp \
           fpos_state.cpp
