######################################################################
# Automatically generated by qmake (3.0) Sun Dec 1 18:35:03 2019
######################################################################

TEMPLATE = app
TARGET = freepos
INCLUDEPATH += ../incl ../../tools/incl
QT += core widgets 
DESTDIR = ../../bin
LIBS += -L../../lib -ltools

# Input
SOURCES += fpos_default.c \
           fpos_func.c \
           fpos_input.c \
           fpos_main.c \
           fpos_state_standby.c
